# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zach walton
email: zacwalt@gmail.com    
description: > # this means to ignore newlines until "baseurl:"
    software engineer @ ï£¿ in the san francisco bay area. good at dance dance revolution. into mountain biking, paddleboarding, backpacking, and video games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zachwalton.com" # the base hostname & protocol for your site
twitter_username: hoofed_locust
github_username:  zachwalton

# Build settings
markdown: kramdown
